language: c

addons:
  apt_packages:
    - libp11-dev
    - libssl-dev
    - libpam0g-dev
    - autopoint

compiler:
  - clang
  - gcc

before_script:
  - ./bootstrap
  - ./configure

script:
  - make distcheck
